name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file dockerfile-master --tag etga7/codeway:$(date +%s)
    - name: Push the Docker image
      run: docker push etga7/codeway:$(date +%s)

